### PR TITLE
Create zh_CN.lang

### PR DESCRIPTION
**Pull request by Mrkwtkr**
Localization Time :D

### CODE REVIEW

**Comment by bonii-xx** [comment]
Wow, that was quick! There are some additional localization strings incoming, I'll wait until I'm sure everything is in before merging. :)

**Comment by Mrkwtkr** [comment]
Remind me when the en_US is finished. :) 
(Quick because Im keep making localizations this summer, enjoying working on these translations.

**Comment by labpaw** [comment]
I am gonna translate it soon too :smile:

**Comment by Mrkwtkr** [comment]
Nice, wait for ur good news ;)

**Pull request closed without merging**
