### PR TITLE
Create zh_CN.lang

### PR DESCRIPTION
**Pull request by Mrkwtkr**

### CODE REVIEW

**Comment by Mrkwtkr** [comment]
Maybe I should chill for a while /w\ , closed it and wait for the completed version.

**Comment by bonii-xx** [comment]
Okay, I think every string for the  next version is in. If you'd be so kind... :)

**Comment by Mrkwtkr** [comment]
Updated it. \o/

**Comment by Mrkwtkr** [comment]
Okay, anybody there?

**Comment by bonii-xx** [comment]
Perfect

**Pull request merged**
